#!/bin/bash
echo "========================================"
echo "    XyraTermux ToolBox"
echo "========================================"
echo ""
echo "Koleksi Informasi & Script Termux"
echo ""
echo "📂 Struktur Project:"
echo "  info/          - Informasi & dokumentasi"
echo "  scripts/       - Script siap pakai"
echo "  docs/          - Troubleshooting & tips"
echo ""
echo "📚 File Penting:"
echo "  info/TERMUX_BASICS.md - Pengenalan Termux"
echo "  info/USEFUL-COMMANDS.md - Perintah berguna"
echo "  docs/TROUBLESHOOTING.md - Solusi masalah"
echo ""
echo "🔧 Script Tersedia:"
echo "  scripts/00-SETUP.sh - Setup environment"
echo "  scripts/01-SYSTEM-INFO.sh - Informasi sistem"
echo "  scripts/02-INSTALL-TOOLS.sh - Install tools"
echo "  scripts/03-BACKUP.sh - Backup config"
echo "  scripts/04-PYTHON-SETUP.sh - Setup Python"
echo ""
echo "========================================"
