#!/bin/bash
echo "========================================"
echo "    TermuxToolBox - Android Project"
echo "========================================"
echo ""
echo "Project Type: Android Native (Java)"
echo "Package: com.termux.toolbox"
echo ""
echo "Features:"
echo "  - Termux API Integration"
echo "  - Custom Command Execution"
echo "  - Quick Install Tools (Python, Node.js, Git, etc.)"
echo "  - Network Tools (Nmap, SSH, cURL, Wget)"
echo "  - System Utilities (Htop, Neofetch, Vim, Nano)"
echo ""
echo "Project Structure:"
echo "  - MainActivity: TermuxToolBox/app/src/main/java/com/termux/toolbox/"
echo "  - Resources: TermuxToolBox/app/src/main/res/"
echo "  - Manifest: TermuxToolBox/app/src/main/AndroidManifest.xml"
echo ""
echo "Java Version:"
java -version 2>&1 | head -1
echo ""
echo "========================================"
